#!/usr/bin/env python3
validation = True
try: 
    from lfit_gui import Application
except ImportError as e :
    validation = False
    print("ImportError: %s" % str(e))
if validation: junk = Application()
