#!/usr/bin/env python3
import sys

validation = True
try: from lfit_script import lfit
except ImportError as e :
    validation = False
    print("ImportError: %s" % str(e))
if validation: 
	junk=lfit()
	if len(sys.argv) !=2:
	   print('Error!')
	   print('Usage: python lfit_script.py <parfile>')
	   sys.exit(1)
	
	junk.generate_bizfile(sys.argv[1])

